---
title: "Everyday Music Listening Portfolio"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(ggplot2)
library(plotly)

library(plotly)
```


Before the experiment 
=====================


Sidebar {.sidebar}
------------------------

We can also add a sidebar



Column 1
-----------------------

###

```{r}
df = data.frame(x = (-10:10), y = (-10:10)^2)
plot(df)
```


Column 2
----------------------

###

```{r}
plot(-df)
```


###
  
we can also put some text here
  
  
Column 3
---------------------



Introduction {.storyboard}
=======================

### Chart 1

```{r}


ggplotly(ggplot(df, aes(x = x, y = y)) +
           geom_point() +
           geom_smooth())

```

*** 

Sample text


### Another chart

```{r}
ggplot(df, aes(x = -x, y = -y)) + 
         geom_point() +
         geom_smooth()
```

*** 

some more text


Methods {.storyboard}
=======================

### Chart 1

```{r}
plot(x=1)
```

***

even more text


Analysis {.storyboard}
======================

###

***

###

***

###

***


Results {.storyboard}
=========================




Discussion 
===================

Col
-------------

### chart

### chart

### chart


Column
--------------


### chart

### chart


Column
--------------

### chart